import { readFileSync } from 'node:fs';
import path from 'node:path';
import examplesData from '@/data/examples.json';

export interface ExampleMeta {
  slug: string;
  workspace: string;
  title: string;
  tagline: string;
  description: string;
  kind: 'intro' | 'deep-dive';
}

export interface ProjectionRoot {
  id: string;
  name: string;
  slug: string;
}

export interface ProjectionNode {
  id: string;
  role: string;
  label: string;
  semanticIds: string[];
}

export interface ProjectionEdge {
  id: string;
  role: string;
  label: string;
  sourceId: string;
  targetId: string;
  semanticIds: string[];
}

export interface ProjectionGraph {
  sourceRevision: number;
  kind: string;
  nodes: ProjectionNode[];
  edges: ProjectionEdge[];
}

export interface ProjectionView {
  supported: boolean;
  error?: string;
  roots?: ProjectionRoot[];
  graph?: ProjectionGraph | null;
}

export interface ExampleSourceDocument {
  path: string;
  content: string;
}

export interface ExampleData {
  slug: string;
  generatedAt: string;
  source: ExampleSourceDocument[];
  views: {
    Lifecycle: ProjectionView;
    RuleDecision: ProjectionView;
  };
}

export const examples: ExampleMeta[] = examplesData as ExampleMeta[];

export function getExample(slug: string): ExampleMeta | undefined {
  return examples.find((example) => example.slug === slug);
}

// Generated by scripts/generate-projections.mjs at build time — never handwritten.
export function getExampleData(slug: string): ExampleData {
  const generatedPath = path.join(process.cwd(), 'src', 'data', 'generated', `${slug}.json`);
  return JSON.parse(readFileSync(generatedPath, 'utf8')) as ExampleData;
}
