<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Modeller.Conformance/Modeller.Conformance.csproj" />
    <ProjectReference Include="../../src/Modeller.Model/Modeller.Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures/**/*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../conformance/**/*.json" Link="Conformance/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
