<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Modeller.Rendering</RootNamespace></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\Modeller.Generation\Modeller.Generation.csproj" /><ProjectReference Include="..\Modeller.Contexts\Modeller.Contexts.csproj" /><ProjectReference Include="..\Modeller.Model\Modeller.Model.csproj" /></ItemGroup>
  <ItemGroup><PackageReference Include="Scriban" /></ItemGroup>
</Project>
